// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgztzlybiwfvpeqwucie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndnenR6bHliaXdmdnBlcXd1Y2llIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NTc0MzAsImV4cCI6MjA2ODMzMzQzMH0.TYIeN2D-aEgczt6GxqfO22s7Tp2Z69QQ7Uko2baQbWA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});